### ISSUE TITLE
Edit Module Metadata doesn't seem to work anymore

### ISSUE THREAD

**Issue by shadowcat-mst** [andk/pause#141]
If I try and go via 'change permissions' I just end up back at the front page.

This is preventing schwern from getting the last of the permissions for Test:: stuff transferred to exodist.

(maybe we should convert all modulelist registrations to first-come perms later?)

**Comment by dagolden** [comment]
It's registered on the module list, right?

I suspect this is due to #130 (@karenetheridge).

Rather than re-enable the module list pages (if only just for admins), I'd prefer to get permissions detached from the module list and back to the other permissions tables (perms? primeur?) in a mass update of some sort.

**Comment by shadowcat-mst** [comment]
I'd love to do that, but right now I'm more interested in being able to mind Test::More and Test::Simple uploaders so we don't end up in some sort of horrible SPOF situation.

I'm basically proposing "re-enable temporarily, then mass update later"

**Comment by karenetheridge** [comment]
@andk is it straightforward to change all 'm' entries in the database to 'f'?
(we can do another pass later to clean things up - like more than one 'f' for a module, or only 'c' but no 'f', etc.)

**Comment by andk** [comment]
>>>>> On Thu, 29 Jan 2015 15:02:22 -0800, shadowcat-mst <notifications@github.com> said:

  > I'd love to do that, but right now I'm more interested in being able to mind
  > Test::More and Test::Simple uploaders so we don't end up in some sort of
  > horrible SPOF situation.

Sorry, I lost it from my radar (a ultra low voltage radar,
unfortunately). I promise to dig into it over the weekend.

-- 
andreas

**Comment by andk** [comment]
For now I handled only Test::More and Test::Simple. Please let me know if that works for immediate needs. On future requests I'll run a bit more, but I'm a coward in running batch jobs.

**Comment by jradcliff** [comment]
I have the same issue with `Google::Ads::AdWords::Client`. Could you flip that to `f` as well? The current owner via `modulelist` is no longer working on that module.

**Comment by andk** [comment]
>>>>> On Tue, 28 Apr 2015 12:31:24 -0700, Josh Radcliff <notifications@github.com> said:

  > I have the same issue with Google::Ads::AdWords::Client. Could you flip that to
  > f as well? The current owner via modulelist is no longer working on that
  > module.

Done. Let me know if you need further flips.

-- 
andreas

**Comment by jradcliff** [comment]
Thanks - that seems to have done the trick. The former module owner (PMATTHEWS) transferred primary membership to me, and now the `peek_perms` page for `PMATTHEWS` still shows `modulelist` for `Google::Ads::AdWords::Client`, but for `JRADCLIFF` I see `first-come`. Is that expected?

**Comment by rjbs** [comment]
I believe this was fully resolved long ago.
